apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: demo-app-repository
  namespace: tekton-polling-operator
spec:
  url: https://github.com/hnts/demo-app.git
  ref: main
  frequency: 5m
  type: github
  pipelineRef:
    name: ci-pipeline
    namespace: tekton-pipelines
    serviceAccountName: pipeline-account
    params:
    - name: gitRevision
      expression: commit.sha
    - name: repoURL
      expression: repoURL
    - name: pathToContext
      expression: "'.'"
    - name: imageUrl
      expression: "'ghcr.io/hnts/demo-app/demo-app'"
    workspaces:
      - name: git-source
        persistentVolumeClaim:
          claimName: tekton-volume